---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: sloats-test-redis-pvc
  labels:
    app: sloats-test-redis
    username: sloats
    env: test
spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: nfs
    resources:
        requests:
            storage: 1Gi

