---
apiVersion: v1
kind: Deployment
metadata:
  name: sloats-test-redis-deployment
  labels:
    username: sloats
    env: test
    app: sloats-test-redis
spec:
  replicas: 1
  selector:
    matchLabels:
        app: sloats-test-redis
  template:
    metadata:
      labels:
        username: sloats
        env: test
  spec:
    containers:
    - image: redis:6
      ports:
      - name: http
        containerPort: 6379
      volumeMounts:
      - mountPath: "/data"
        name: redis-test-volume
    volumes:
    - name: sloats-test-redis-pvc 
      persistantVolumeClaim:
          claimName: sloats-test-redis-pvc
      
